version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: projet-web-nest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

volumes:
  postgres_data:
